### ISSUE TITLE
Case sensitive query using fuzzy search

### ISSUE THREAD

**Issue by andy3rdworld** [polyfractal/sherlock#67] opened 2013-06-26 22:41 UTC
Modifying the documentation examples a bit, if I run the below code to create an index and push a document there appears to be a case-sensitivity issue (different results) between fuzzy and 'standard' searches. Is this the behavior I should expect?

``` php
public static function buildElasticSearchIndexes()
  {     
        //$settings = array('refresh_interval' =>'1s', 'number_of_replicas' => 2)

        $sherlock = new Sherlock;
        $sherlock->addNode("localhost", 9200);

        //Create an index object, passing the index name in the constructor
        //All index operations (create, update, delete, etc) will go through this object.
        $index = $sherlock->index( 'topicindex' );

        //Let's add some settings
        //$settings = Sherlock::indexSettings()->refresh_interval("1s")
          //                                 ->number_of_replicas(2);

        //Add mappings
        $mapping = Sherlock::mappingBuilder('topic')->String()
                                                       ->field('title_display');
        $mapping2 = Sherlock::mappingBuilder('topic')->String()
                                                       ->field('description');
        $mapping3 = Sherlock::mappingBuilder('topic')->String()
                                                       ->field('category');

        //Set the mappings and settings in one method-chained line
        //$index->settings($settings)->mappings($mapping, $mapping2, $mapping3);
        $index->mappings($mapping, $mapping2, $mapping3);

        //Create the index.  This will apply whatever settings have been configured
        $response = $index->create();

        //This will say "true" if successful
        echo $response->ok;

        //Delete the index
        //$response = $index->delete();

        return $response->ok;
  }

  public static function addElasticSearchDocument($data, $index = 'topicindex', $index_type = 'topic')
  {
        $sherlock = new Sherlock;
        $sherlock->addNode("localhost", 9200);

        // an index and type are specified in addition to the document
        $doc = $sherlock->document()->index($index)->type($index_type)->document($data);

        // execute the indexing request
        return $doc->execute();

  }

  public static function search($query, $fuzzy = true, $from = 0, $size = 10, $provider = 'ElasticSearch')
  {
        //The Sherlock object manages cluster state, builds queries, etc
       $sherlock = new Sherlock();

       //Add a node to our cluster.  Sherlock can optionally autodetect nodes given one starting seed
       $sherlock->addNode('localhost', 9200);

       //Build a new search request
       $request = $sherlock->search();

       //Set the index, type and from/to parameters of the request.
       //The query is at at the end of the chain, although it could be placed anywhere
       if( $fuzzy ) {
          $request->index('topicindex')
                ->type('topic')
                ->from($from)
                ->size($size)
                ->query(Sherlock::queryBuilder()
                  ->FuzzyLikeThis()
                  ->fields( array('description', 'title_display') ) 
                  ->like_text($query)
                  ->min_similarity(0.6)
                  );
       } else {          
          $request->index('topicindex')
                ->type('topic')
                ->from($from)
                ->size($size)
                ->query(Sherlock::queryBuilder()->Term()->field('description')
                                                  ->term($query)); 
       }

       //Execute the search and return results
       $response = $request->execute();

       echo "Took: ".$response->took."\r\n";
       echo "Number of Hits: ".count($response)."\r\n";

       //Iterate over the hits and print out some data
       foreach($response as $hit)
       {
          var_dump($hit);
          //echo $hit['score'].' - '.$hit['source']['message']."\r\n";
       }

       return true;
  }

data = array('title_display' => 'Chateau de Versailles',
                        //'description' => 'The Palace of Versailles (/vɛərˈsaɪ/ vair-SY or /vərˈsaɪ/ vər-SY; French: [vɛʁˈsɑj]), or simply Versailles, is a royal château in Versailles in the Île-de-France region of France. In French it is the Château de Versailles. When the château was built, Versailles was a country village; today, however, it is a wealthy suburb of Paris, some 20 kilometres southwest of the French capital. The court of Versailles was the centre of political power in France from 1682, when Louis XIV moved from Paris, until the royal family was forced to return to the capital in October 1789 after the beginning of the French Revolution. Versailles is therefore famous not only as a building, but as a symbol of the system of absolute monarchy of the Ancien Régime.',
                        'description' => 'this is a test description of the palace of versailles, a french palace located outside the city of Paris.',
                        'category' => 'Travel');
buildElasticSearchIndexes();
addElasticSearchDocument($data);
var_dump(search('paris'));
echo '<br>';
var_dump(search('paris', $fuzzy = false));
echo '<br>';
var_dump(search('Paris'));
echo '<br>';
var_dump(search('Paris', $fuzzy = false));
```

**Comment by polyfractal** [comment] 2013-06-27 02:42
Yep, that's expected behavior.  When creating your mapping, you don't define an analyzer, so Elasticsearch is defaulting to the [Standard Analyzer](http://www.elasticsearch.org/guide/reference/index-modules/analysis/standard-analyzer/).  This automatically lowercases tokens before indexing.

When searching with FuzzyLikeThis, Elasticsearch is using the analyzer associated with the field to parse your query (the Standard Analyzer mentioned above), so your search query is lowercased. 

However, the [Term Query](http://www.elasticsearch.org/guide/reference/query-dsl/terms-query/) does not go through an analysis process - it is looking for your exact search query (case sensitivity and all) in the index.  But that doesn't exist, because the Standard Analyzer has lowercased everything.

Try changing your Term Query to a [Match Query](http://www.elasticsearch.org/guide/reference/query-dsl/match-query/) for a more generic "search box" search.

As a side note: the FuzzyLikeThis query is a really strange query anyway.  It's constructing a MoreLikeThis (also a weird query) with fuzzy matching based on Levenshtein edits.  You may want to consider just a normal [Fuzzy](http://www.elasticsearch.org/guide/reference/query-dsl/fuzzy-query/) query.

**Comment by andy3rdworld** [comment] 2013-06-27 19:59
Ok, thanks...just playing around with your code trying to test an autocomplete search box that could ideally handle some misspelling. I've been using Redis successfully using ngrams (from start of query) by adapting http://oldblog.antirez.com/post/autocomplete-with-redis.html but would like minor misspelling accounted for as well. Do you have any recommendations on a good approach (gets more at your expertise in Elasticsearch rather that Sherlock specifically, I suppose)? Here's a blog that explains one possible Elasticsearch configuration to some extent: http://jontai.me/blog/2013/02/adding-autocomplete-to-an-elasticsearch-search-application/

Something like this using basic fuzzy works reasonably well in some quick and dirty tests as you suggested, but my sense is that with so many people working on this problem there's probably some more advanced query "optimized" for autocomplete through much trial and error.

``` php
$json = '{ "fuzzy" : { "description" : { "value" : "' .  $query . '", "prefix_length" : 0, "min_similarity" : 0.5, "boost" : 1.0 } } }';
```

**Comment by polyfractal** [comment] 2013-06-28 13:57
So there are a few ways to deal with mis-spellings, depending on where you want to trade performance.
- FuzzyQuery uses CPU at query time, because it parses your query and constructs probably edits using Levenshtein distance (basically, how many characters do you need to replace to make a term in the index)
- Match_phrase_prefix is a good candiate for "as you type" suggestions.  It also uses CPU at query time.  It will tolerate spelling mistakes in the portion of the query that hasn't been typed yet, but will not correct the part of the query already provided by the user.  It only helps with autocomplete basically, not spelling. [I wrote an article a while ago about how to do that.](http://euphonious-intuition.com/2013/02/starts-with-phrase-matching-in-elasticsearch/)
- N-grams (the link you posted) can be used for both spelling corrections to some degree and autocomplete.  It uses CPU at indexing time, so you pay the price "up front" instead of while querying.  It also bloats your physical index size, potentially a lot depending on how many ngrams you configure.
- Lastly, you could use the new [Suggest API](http://www.elasticsearch.org/guide/reference/api/search/suggest/).  This API internally works similar to the Fuzzy query (Levenshtein distance, etc), but provides an endpoint to get probably suggestions.  So instead of transparently guessing at spelling mistakes and correcting for the user, you provide a "Did you mean xyz?" to the user and allow them to select it.  This is how Google does spelling mistakes in most of their searches.

**Comment by Mopster** [comment] 2013-06-28 14:11
You could also add a fuzziness factor to your Match query, that's how I'm doing it now until I find something better (multi search, analyzers, ...) :)

**Comment by polyfractal** [comment] 2013-06-28 14:28
Ah, that too :)

(Technically, you can do all sorts of wizardry with the Query String query too...but don't, it's a dangerous tool)

**Comment by andy3rdworld** [comment] 2013-06-28 15:33
Good tips - off to experiment with Suggest.

**Comment by polyfractal** [comment] 2013-07-01 12:16
Gonna close this...reopen if you have any more questions :)

**Closed as completed by polyfractal** 2013-07-01 12:16 UTC
